### ISSUE TITLE
Error messages when trying to use template

### ISSUE THREAD

**Issue by AletteS** [datadesk/baker-example-page-template#5]
Hi there

I am a journalism lecturer trying to learn how to use your template and a bit stuck. I have followed the instructions up to NPM install and NPM start and get the follow error messages. I was hoping there is perhaps an easy fix out there you could share with me:
 $ npm install
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\User\\Code\\my-visual-story\\node_modules\\@babel\\plugin-syntax-typescript',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\User\Code\my-visual-story\node_modules\@babel\plugin-syntax-typescript\test\fixtures\disallow-jsx-ambiguity'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\User\\Code\\my-visual-story\\node_modules\\@babel\\plugin-syntax-typescript\\test\\fixtures\\disallow-jsx-ambiguity'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\User\\Code\\my-visual-story\\node_modules\\date-fns',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\User\Code\my-visual-story\node_modules\date-fns\esm\locale\pt-BR'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\User\\Code\\my-visual-story\\node_modules\\date-fns\\esm\\locale\\pt-BR'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm notice
npm notice New minor version of npm available! 9.5.1 -> 9.6.7
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.7
npm notice Run npm install -g npm@9.6.7 to update!
npm notice
npm ERR! code 1
npm ERR! path C:\Users\User\Code\my-visual-story\node_modules\@vercel\git-hooks
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./install.js
npm ERR! △  @vercel/git-hooks: installing base hook to C:\Users\User\Code\my-visual-story\.git\hooks
npm ERR! node:internal/fs/utils:347
npm ERR!     throw err;
npm ERR!     ^
npm ERR!
npm ERR! Error: EPERM: operation not permitted, symlink './_do_hook.cjs' -> 'C:\Users\User\Code\my-visual-story\.git\hooks\applypatch-msg'
npm ERR!     at Object.symlinkSync (node:fs:1741:3)
npm ERR!     at installHook (C:\Users\User\Code\my-visual-story\node_modules\@vercel\git-hooks\install.js:122:5)
npm ERR!     at Array.forEach (<anonymous>)
npm ERR!     at Object.<anonymous> (C:\Users\User\Code\my-visual-story\node_modules\@vercel\git-hooks\install.js:146:3)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   errno: -4048,
npm ERR!   syscall: 'symlink',
npm ERR!   code: 'EPERM',
npm ERR!   path: './_do_hook.cjs',
npm ERR!   dest: 'C:\\Users\\User\\Code\\my-visual-story\\.git\\hooks\\applypatch-msg'
npm ERR! }
npm ERR!
npm ERR! Node.js v18.16.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2023-06-04T17_25_50_852Z-debug-0.log

User@DESKTOP-K8DQT6J MINGW64 ~/Code/my-visual-story (main)
$ npm start

> start
> NODE_ENV=development bake serve --config

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Comment by palewire** [comment]
Hey. I'm just seeing this message. Sorry for the delay in responding. Can you email me at b@palewi.re or ben.welsh@thomsonreuters.com? I'd be happy to help you sort this out.

**Comment by palewire** [comment]
I'm going to close this as stale. If you still have questions, please email me at the address above.
